from openai import OpenAI
from typing import Dict, Any
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.helpers import log_agent_action, format_sources, save_report
from config import Config

class ReportAgent:
    """Agent responsible for creating structured reports"""
    
    def __init__(self, api_key: str):
        self.demo_mode = Config.DEMO_MODE
        
        # Only initialize OpenAI client if not in demo mode
        if not self.demo_mode:
            self.client = OpenAI(api_key=api_key)
        else:
            self.client = None
            print("✅ Report Agent initialized in demo mode")
        
        self.name = "ReportAgent"
    
    def generate_report(self, analysis_data: Dict[str, Any], reports_dir: str) -> str:
        """
        Generate a comprehensive research report
        
        Args:
            analysis_data: Data from AnalyzerAgent
            reports_dir: Directory to save report
            
        Returns:
            Path to saved report
        """
        log_agent_action(self.name, "Generating report", analysis_data['topic'])
        
        # Create report structure
        report = self._create_report_structure(analysis_data)
        
        # Enhance with AI (or skip in demo mode)
        if not self.demo_mode:
            enhanced_report = self._enhance_with_ai(analysis_data['topic'], report)
        else:
            enhanced_report = report
            log_agent_action(self.name, "Using demo report (no AI enhancement)")
        
        # Save report
        filepath = save_report(enhanced_report, analysis_data['topic'], reports_dir)
        
        log_agent_action(self.name, "Report complete", filepath)
        
        return filepath
    
    def _create_report_structure(self, data: Dict[str, Any]) -> str:
        """Create the basic report structure"""
        
        topic = data['topic']
        insights = data['insights']
        keywords = data['keywords']
        sources = data['sources']
        key_points = data.get('key_points', [])
        
        report = f"""# Research Report: {topic}

---

## Executive Summary

{insights.get('overview', 'Overview of research findings on ' + topic + '.')}

---

## Key Findings

{insights.get('key_findings', 'Analysis reveals multiple important aspects of ' + topic + '.')}

---

## Keywords and Themes

{', '.join(keywords) if keywords else 'No keywords extracted'}

---

## Implications and Applications

{insights.get('implications', 'The research indicates significant potential for practical applications and further development.')}

---

## Detailed Insights

"""
        
        # Add key points
        if key_points:
            report += "\n### Important Points:\n\n"
            for i, point in enumerate(key_points[:5], 1):
                report += f"{i}. {point}\n"
        
        # Add sources
        report += "\n\n" + format_sources(sources)
        
        report += f"\n\n---\n*Report generated by AI Research Assistant*\n"
        if self.demo_mode:
            report += "*Generated in Demo Mode with sample data*\n"
        
        return report
    
    def _enhance_with_ai(self, topic: str, report: str) -> str:
        """
        Use AI to enhance and polish the report
        
        Args:
            topic: Research topic
            report: Initial report text
            
        Returns:
            Enhanced report
        """
        log_agent_action(self.name, "Enhancing report with AI")
        
        prompt = f"""You are a professional research report writer. 
Improve the following research report about "{topic}" by:
1. Making it more coherent and well-structured
2. Ensuring professional tone
3. Adding transitional phrases where needed
4. Keeping all factual information and sources intact

Original Report:
{report}

Return the improved version maintaining the markdown format."""

        try:
            response = self.client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a professional report editor."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=2000
            )
            
            enhanced = response.choices[0].message.content.strip()
            return enhanced
            
        except Exception as e:
            log_agent_action(self.name, "ERROR enhancing report", str(e))
            return report  # Return original if enhancement fails